require "options"
require "keymaps"
require "plugins"

-- Require plugin settings
require "plugin-settings.impatient"
require "plugin-settings.alpha-nvim"
require "plugin-settings.nvim-cmp"
require "plugin-settings.telescope"
require "plugin-settings.bufferline"
require "plugin-settings.autopairs"
require "plugin-settings.comment"
require "plugin-settings.nvim-tree"
require "plugin-settings.lualine"
require "plugin-settings.gitsigns"
require "plugin-settings.nvim-treesitter"
require "plugin-settings.indent-blankline"
require "plugin-settings.project-nvim"
require "plugin-settings.toggleterm-nvim"
require "plugin-settings.which-key"
require "plugin-settings.nvim-dap"
require "plugin-settings.dapinstall"
require "plugin-settings.neogen"
require "lsp"

require "colorscheme"
