return {
	{
		"mason-org/mason.nvim",
		event = { "BufReadPre", "BufNewFile" },
		cmd = "Mason",
		opts = {},
	},
	{
		"WhoIsSethDaniel/mason-tool-installer.nvim",
		event = { "VimEnter", "BufReadPre", "BufNewFile" },
		cmd = "MasonToolInstall",
		dependencies = {
			"mason-org/mason.nvim",
		},
		opts = {
			ensure_installed = {
				"clangd",
				"clang-format",
				"css-lsp",
				"emmet-language-server",
				"eslint-lsp",
				"eslint_d",
				"html-lsp",
				"intelephense",
				"lua-language-server",
				"phpcs",
				"php-cs-fixer",
				"php-debug-adapter",
				"phpstan",
				"pint",
				"prettier",
				"stylelint-lsp",
				"stylua",
				"tailwindcss-language-server",
				"typescript-language-server",
				"vue-language-server",
			},
			run_on_start = true,
		},
	},
}
